feat(community): add page create member file on github
betagouv/espace-membre-next pull request #137
Opened 2024-03-04 16:36 UTC by LucasCharrier

2024-03-15 11:45 UTC, revolunet commented on src/app/(private)/(dashboard)/account/base-info/page.tsx
> +    });
besoin ici ?

2024-03-15 11:49 UTC, revolunet commented on src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
> +            // todo: sentry
un petit `Sentry.captureException(e)` ici c'est un cas anormal

2024-03-15 11:49 UTC, revolunet commented on src/app/(private)/(dashboard)/community/create/page.tsx
> +    const username = session.id;
```suggestion
```

2024-03-18 08:40 UTC, revolunet commented on src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
> +                                            nativeInputProps={{
ici peut-être ajouter une information pour être sûrs qu'ils mettent un email PRO ? et officiel si la personne en a déjà un ?

2024-03-18 08:42 UTC, revolunet commented on src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
> +                                            label="Prénom"
Pas très important mais pour info tu peux récupérer la description zod avec un truc comme ça:
```suggestion
                                            label={createMemberSchema.shape.firstname.description}
```

2024-03-18 08:43 UTC, revolunet commented on src/app/(private)/(dashboard)/community/create/CommunityCreateMemberPage.tsx
> +                        Une fois la fiche validée, {firstname} {lastname}{" "}
```suggestion
                        Une fois la fiche validée et mergée, {firstname} {lastname}{" "}
```

2024-03-18 08:45 UTC, revolunet commented on src/app/api/member/[username]/route.ts
> +    const data = await req.json();
Ici il faut s'assurer que le user est bien loggué/identifié. c'est dans un middleware ?

2024-03-18 08:48 UTC, revolunet commented on src/app/api/member/route.ts
> +    const data = await req.json();
vérifier l'auth ici ? middleware ?

2024-03-18 08:49 UTC, revolunet commented
Je n'ai pas compris pour quoi `src/app/api/member/[username]/route.ts` et `src/app/api/member/route.ts`. il y a p-e du code à factoriser ici

2024-03-18 08:53 UTC, revolunet commented on src/models/member.ts
> +                message: "Le champs gender est obligatoire",
```suggestion
                message: "Le champ gender est obligatoire",
```

2024-03-19 17:03 UTC, LucasCharrier commented
Bon j'ai fait les updates, mais depuis que j'ai rebased ça ne build plus, je cherche le fix.

2024-03-19 18:41 UTC, LucasCharrier commented
@revolunet @astranchet vous pouvez tester la review app, même si c'est une v1, je pense qu'il y a quelques trucs a ajouter. Actuellement l'email sera créé après la partie vérification mais rien ne l'indique à l'utilisateur. Il faudrait donc ajouter un message dans l'espace-membre, pour que la personne soit au courant.

2024-03-20 08:28 UTC, revolunet commented
on peut enlever le bloc "créer ma fiche" sur la home ?

2024-03-20 13:27 UTC, astranchet commented
@LucasCharrier je ne sais pas comment tester (j'ai tenté de me connecter avec ton mail beta, mais ça me dit que L'adresse email lucas.charrier@beta.gouv.fr est inconnue.

2024-03-20 14:12 UTC, astranchet commented
@revolunet possibilité de voir le wording en live (sur une instance ou en screenshot ?)

2024-03-20 14:21 UTC, revolunet commented
<img width="756" alt="Capture d’écran 2024-03-20 à 15 21 42" src="https://github.com/betagouv/espace-membre-next/assets/124937/31c12429-8c57-4e45-9c4a-ff7cd640b0e6">

2024-03-20 14:56 UTC, astranchet requested changes
Petits changements de wording sur l'étape 1 : 
- "Début de ta mission" => "Début de la mission" (puisqu'une autre personne rempli le truc
- "Un email professionel qui nous servira pour lui envoyer les informations relatives à son compte" => "Nous enverrons les informations relatives au compte à cet email"
- Faut-il mettre ici la coche "je veux pas de mail beta" d'ailleurs ?
- "Entité avec qui tu as contractualisé" => "Entité qui gère la contractualisation"
- le "En cas de doute mettre J+3 mois" est réactif au survol mais rien ne se passe au clic. Pourquoi ?

2024-03-20 15:55 UTC, astranchet commented
Sur la partie 2 (quand la personne se connecte) : 

"Rôle actuel, ex: UX designer", l'exemple doit être en description
![image](https://github.com/betagouv/espace-membre-next/assets/1374389/1fbe9522-55e8-4d1f-a8ee-ef4c7c10f128)

"Mission 1" => possibilité de virer le 1, puisqu'à ce stade y en a qu'une ?

Et sinon, il reste à splitter en étapes. Ça serait dans un second temps ?

2024-03-20 16:27 UTC, LucasCharrier commented
> Petits changements de wording sur l'étape 1 :
> 
> * "Début de ta mission" => "Début de la mission" (puisqu'une autre personne rempli le truc
> * "Un email professionel qui nous servira pour lui envoyer les informations relatives à son compte" => "Nous enverrons les informations relatives au compte à cet email"
> * Faut-il mettre ici la coche "je veux pas de mail beta" d'ailleurs ?
> * "Entité avec qui tu as contractualisé" => "Entité qui gère la contractualisation"
> * le "En cas de doute mettre J+3 mois" est réactif au survol mais rien ne se passe au clic. Pourquoi ?

yes j'ai voulu utilisé un composant existant mais c'était pas un bon mouv je pense, je vais updaté.

2024-03-20 17:25 UTC, LucasCharrier commented
> * Nous enverrons les informations relatives au compte à cet email

Ok c'est fait.
Pour la demande d'email beta, on va faire comme ajd pour l'instant, si l'email renseigné est un email de service public on ne crée pas d'adresse, si l'email est un autre type d'email on crée automatiquement.

2024-03-20 17:27 UTC, LucasCharrier commented
> Sur la partie 2 (quand la personne se connecte) :
> 
> "Rôle actuel, ex: UX designer", l'exemple doit être en description ![image](https://private-user-images.githubusercontent.com/1374389/314571240-1fbe9522-55e8-4d1f-a8ee-ef4c7c10f128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTE3MTksIm5iZiI6MTcxMDk1MTQxOSwicGF0aCI6Ii8xMzc0Mzg5LzMxNDU3MTI0MC0xZmJlOTUyMi01NWU4LTRkMWYtYThlZS1lZjRjN2MxMGYxMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTYxNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI5Y2JjMDQzN2MyODVmYmY0MmUxYWE0NzZjY2NjMDgyY2ZmNTljYWMzNmZjYTBkYWFkMjcxZjRjMjk5YjY5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.69U6etaXZxgAhv-hIQmDwlwSWvPEuxt12Y-KHUUCXUA)
> 
> "Mission 1" => possibilité de virer le 1, puisqu'à ce stade y en a qu'une ?
> 
> Et sinon, il reste à splitter en étapes. Ça serait dans un second temps ?

Yes c'est fait. 
Oui, on voudrait merger le comportement actuel cette semaine pour lancer une campagne de pentest YesWeHack. Et on update dans une v2 dans les semaines à venir.

2024-03-21 17:11 UTC, LucasCharrier commented
- [ ] ajoute `Un membre de la communauté doit créer ta fiche depuis l'espace-membre. Tu recevras un lien de connexion quand celle-ci sera validée`
- [ ] regarder le cas des `attributaire`
- [ ] ajouter les compétences dans le formulaire 2

2024-03-22 07:46 UTC, revolunet approved these changes

2024-03-22 07:47 UTC, merged