chore: removed sidemenu, add submenu to dropdown
betagouv/espace-membre-next pull request #643
Opened 2024-11-14 11:31 UTC by LucasCharrier

2024-11-20 22:35 UTC, revolunet commented on src/app/(private)/(dashboard)/organizations/[id]/info-form/page.tsx
> +    console.log("LCS TOTO 1", organization.uuid);
```suggestion
```

2024-11-26 10:00 UTC, LucasCharrier commented
Du coup explorer la communauté > communauté > membres | produit | ...
je me demande si ça fait pas trop d'intrication.
Sachant qu'on peut avoir qu'un niveau de sous-menu avec le dsfr, donc "produit", "membre", ... serait cacher sous communauté.
Est-ce que observatoire et carte des membres ne devrait pas d'une façon ou d'une autre etre présenté sur la page membre.

2024-11-26 10:09 UTC, LucasCharrier commented
Dans la version d' @astranchet il y a en encart carte des membres en dessous de la liste de membres. Mais en effet, on le voit pas avec une liste longue. 

2 propositions :
1. Mettre deux encart au debut de page : Carte des membres et observatoire. Et la recherche des membres en dessous.
2. La page membre devient une sorte de page d'accueil membre, et on a 3 encarts (comme sur la page dashboard) : Recherche des membres, carte des membres et observatoire.

2024-11-26 10:19 UTC, revolunet approved these changes

2024-11-26 10:19 UTC, astranchet commented
Mémoire de poisson rouge, je retiens jamais comment s'authentifier sur Scalingo. Je pensais avec valid member, mais non : 
![image](https://github.com/user-attachments/assets/94c39f62-b33a-4e85-b186-c9a55064e255)

2024-11-26 10:21 UTC, astranchet commented
Je sortirai bien du menu "Communauté" les entrées "Membres" et "Produits" qui sont le nerf de la guerre et nos pages les plus importantes. Effectivement d'accord avec toi @LucasCharrier, c'est un peu trop caché là je pense.

2024-11-26 10:23 UTC, astranchet commented
Et d'accord aussi sur la proposition de mettre l'encart Carte des membres sur la home

2024-11-26 10:24 UTC, astranchet requested changes
Garder une entrée spécifique pour Membres et Produits en niveau 1 du menu (pages principales de l'espace membre). Sinon, c'est trop cool !

2024-11-26 13:05 UTC, merged